// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "Admin": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/zenoss/zenkit/admin/design
// --out=$(GOPATH)/src/github.com/zenoss/zenkit/admin
// --version=v1.3.0

package app
